### ISSUE TITLE
deploy to Dokku

### ISSUE THREAD

**Issue by yegor256** [yegor256/soalition#25]

**Comment by yegor256** [comment]
@rultor release, tag is `0.4.4`

**Comment by yegor256** [comment]
@rultor release, tag is `0.4.4`

**Comment by 0crat** [comment]
Job `gh:yegor256/soalition#25` is not assigned, can't get performer

**Comment by yegor256** [comment]
@rultor release, tag is `0.4.5`

**Comment by yegor256** [comment]
@rultor release, tag is `0.4.5`

**Comment by 0crat** [comment]
Job `gh:yegor256/soalition#25` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
