### ISSUE TITLE
kick out the least productive

### ISSUE THREAD

**Issue by yegor256** [yegor256/soalition#9]

**Comment by driver733** [comment]
#7 Related

**Comment by driver733** [comment]
I know that we have a scoring system, but the members of groups are supposed to write posts, not just report others' posts. I suggest that we should implement minimum passing requirements, such as writing X number of posts per 30 days. (Let's say, 1 post per month).
@yegor256 WDYT?

**Comment by yegor256** [comment]
@yegor256 I like it, we'll implement now

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.0`
